name: Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest

      - name: Bump version
        id: bump-version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          NEW_VERSION=$(clojure -T:build bump-version :type :${{ github.event.inputs.version-type }})
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Push changes and tags
        run: |
          git push origin main
          git push origin --tags

      - name: Test & build JAR
        run: clojure -T:build ci

      - name: Deploy to Clojars
        run: clojure -T:build deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-version.outputs.new_version }}
          name: Release ${{ steps.bump-version.outputs.new_version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}